name: GitHub Actions Demo
on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 10 * * *'  
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Output event name
        run: echo ${{ github.event_name }}

      - name: Output branch name
        run: echo ${{ github.ref_name }}

      - name: List repository files
        run: ls -R
